//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stork_Future_TaoLi.StockInfoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockInfoService.IDomainService")]
    public interface IDomainService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDomainService/ProvidePolicyFile", ReplyAction="http://tempuri.org/IDomainService/ProvidePolicyFileResponse")]
        System.ServiceModel.Channels.Message ProvidePolicyFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDomainService/ProvidePolicyFile", ReplyAction="http://tempuri.org/IDomainService/ProvidePolicyFileResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> ProvidePolicyFileAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDomainServiceChannel : Stork_Future_TaoLi.StockInfoService.IDomainService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DomainServiceClient : System.ServiceModel.ClientBase<Stork_Future_TaoLi.StockInfoService.IDomainService>, Stork_Future_TaoLi.StockInfoService.IDomainService {
        
        public DomainServiceClient() {
        }
        
        public DomainServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DomainServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DomainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DomainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Channels.Message ProvidePolicyFile() {
            return base.Channel.ProvidePolicyFile();
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> ProvidePolicyFileAsync() {
            return base.Channel.ProvidePolicyFileAsync();
        }
    }
}
