//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stork_Future_TaoLi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BWNameTable
    {
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string Amount { get; set; }
        public Nullable<double> PercentageA { get; set; }
        public string Value { get; set; }
        public Nullable<double> PercentageB { get; set; }
        public Nullable<bool> flag { get; set; }
        public string securityName { get; set; }
    }
}
