//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stork_Future_TaoLi.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoneyEntityEntities1 : DbContext
    {
        public MoneyEntityEntities1()
            : base("name=MoneyEntityEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CC_TAOLI_TABLE> CC_TAOLI_TABLE { get; set; }
        public DbSet<DL_TAOLI_TABLE> DL_TAOLI_TABLE { get; set; }
        public DbSet<SG_TAOLI_OPEN_TABLE> SG_TAOLI_OPEN_TABLE { get; set; }
        public DbSet<SG_TAOLI_STATUS_TABLE> SG_TAOLI_STATUS_TABLE { get; set; }
        public DbSet<SG_TAOLI_CLOSE_TABLE> SG_TAOLI_CLOSE_TABLE { get; set; }
        public DbSet<ER_TAOLI_TABLE> ER_TAOLI_TABLE { get; set; }
        public DbSet<OL_TAOLI_LIST_TABLE> OL_TAOLI_LIST_TABLE { get; set; }
    }
}
