//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stork_Future_TaoLi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DL_TAOLI_TABLE
    {
        public System.Guid DL_GUID { get; set; }
        public string DL_STRATEGY { get; set; }
        public string DL_DIRECTION { get; set; }
        public string DL_OFFSETFLAG { get; set; }
        public string DL_CODE { get; set; }
        public string DL_NAME { get; set; }
        public string DL_STATUS { get; set; }
        public string DL_TYPE { get; set; }
        public Nullable<int> DL_STOCK_AMOUNT { get; set; }
        public Nullable<double> DL_BARGAIN_PRICE { get; set; }
        public Nullable<double> DL_BARGAIN_MONEY { get; set; }
        public string DL_BARGAIN_TIME { get; set; }
        public string DL_NO { get; set; }
        public Nullable<bool> DL_LOAD { get; set; }
        public string DL_USER { get; set; }
        public string DL_MARK { get; set; }
    }
}
