//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stork_Future_TaoLi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OL_TAOLI_LIST_TABLE
    {
        public System.Guid OL_GUID { get; set; }
        public string OL_LIST { get; set; }
        public Nullable<System.DateTime> OL_TIME { get; set; }
        public string SG_ID { get; set; }
    }
}
