//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stork_Future_TaoLi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISK_TABLE
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string alias { get; set; }
        public string strategy_id { get; set; }
        public string err { get; set; }
        public string code { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<double> price { get; set; }
        public string orientation { get; set; }
    }
}
