//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stork_Future_TaoLi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_TAOLI_CLOSE_TABLE
    {
        public System.Guid SG_GUID { get; set; }
        public string SG_ID { get; set; }
        public string SG_OPEN_ID { get; set; }
        public string SG_INIT_POSITION_LIST { get; set; }
        public string SG_LATEST_POSITION_LIST { get; set; }
        public string SG_FUTURE_CONTRACT { get; set; }
        public Nullable<int> SG_SHORT_POINT { get; set; }
        public Nullable<int> SG_HAND { get; set; }
        public Nullable<double> SG_COE { get; set; }
        public Nullable<double> SG_SD { get; set; }
        public Nullable<double> SG_SA { get; set; }
        public Nullable<double> SG_PE { get; set; }
        public Nullable<double> SG_BAS { get; set; }
        public Nullable<int> SG_STATUS { get; set; }
        public Nullable<System.DateTime> SG_CREATE_TIME { get; set; }
        public string SG_USER { get; set; }
    }
}
