//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stork_Future_TaoLi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_TAOLI_OPEN_TABLE
    {
        public System.Guid SG_GUID { get; set; }
        public string SG_ID { get; set; }
        public string SG_Contract { get; set; }
        public Nullable<double> SG_OP_POINT { get; set; }
        public Nullable<int> SG_HAND_NUM { get; set; }
        public Nullable<int> SG_INDEX { get; set; }
        public string SG_WEIGHT_LIST { get; set; }
        public string SG_INIT_TRADE_LIST { get; set; }
        public string SG_LATEST_TRADE_LIST { get; set; }
        public Nullable<int> SG_STATUS { get; set; }
        public Nullable<System.DateTime> SG_CREATE_TIME { get; set; }
        public string SG_USER { get; set; }
    }
}
