//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stork_Future_TaoLi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public System.Guid ID { get; set; }
        public string alias { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string stockAvailable { get; set; }
        public string futureAvailable { get; set; }
        public Nullable<int> userRight { get; set; }
    }
}
