//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.6387
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://MarketInfoSys", ClrNamespace = "marketinfosys")]

namespace marketinfosys
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MarketData", Namespace = "http://MarketInfoSys")]
    public partial class MarketData : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int ActionDayField;

        private uint[] AskPriceField;

        private uint[] AskVolField;

        private uint[] BidPriceField;

        private uint[] BidVolField;

        private string CodeField;

        private uint HighField;

        private uint HighLimitedField;

        private int IOPVField;

        private uint LowField;

        private uint LowLimitedField;

        private uint MatchField;

        private uint NumTradesField;

        private uint OpenField;

        private uint PreCloseField;

        private byte[] PrefixField;

        private int SD2Field;

        private int StatusField;

        private int Syl1Field;

        private int Syl2Field;

        private int TimeField;

        private long TotalAskVolField;

        private long TotalBidVolField;

        private int TradingDayField;

        private long TurnoverField;

        private long VolumeField;

        private uint WeightedAvgAskPriceField;

        private uint WeightedAvgBidPriceField;

        private string WindCodeField;

        private int YieldToMaturityField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActionDay
        {
            get
            {
                return this.ActionDayField;
            }
            set
            {
                this.ActionDayField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint[] AskPrice
        {
            get
            {
                return this.AskPriceField;
            }
            set
            {
                this.AskPriceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint[] AskVol
        {
            get
            {
                return this.AskVolField;
            }
            set
            {
                this.AskVolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint[] BidPrice
        {
            get
            {
                return this.BidPriceField;
            }
            set
            {
                this.BidPriceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint[] BidVol
        {
            get
            {
                return this.BidVolField;
            }
            set
            {
                this.BidVolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint High
        {
            get
            {
                return this.HighField;
            }
            set
            {
                this.HighField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint HighLimited
        {
            get
            {
                return this.HighLimitedField;
            }
            set
            {
                this.HighLimitedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IOPV
        {
            get
            {
                return this.IOPVField;
            }
            set
            {
                this.IOPVField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Low
        {
            get
            {
                return this.LowField;
            }
            set
            {
                this.LowField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint LowLimited
        {
            get
            {
                return this.LowLimitedField;
            }
            set
            {
                this.LowLimitedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Match
        {
            get
            {
                return this.MatchField;
            }
            set
            {
                this.MatchField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint NumTrades
        {
            get
            {
                return this.NumTradesField;
            }
            set
            {
                this.NumTradesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Open
        {
            get
            {
                return this.OpenField;
            }
            set
            {
                this.OpenField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint PreClose
        {
            get
            {
                return this.PreCloseField;
            }
            set
            {
                this.PreCloseField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Prefix
        {
            get
            {
                return this.PrefixField;
            }
            set
            {
                this.PrefixField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SD2
        {
            get
            {
                return this.SD2Field;
            }
            set
            {
                this.SD2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Syl1
        {
            get
            {
                return this.Syl1Field;
            }
            set
            {
                this.Syl1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Syl2
        {
            get
            {
                return this.Syl2Field;
            }
            set
            {
                this.Syl2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Time
        {
            get
            {
                return this.TimeField;
            }
            set
            {
                this.TimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalAskVol
        {
            get
            {
                return this.TotalAskVolField;
            }
            set
            {
                this.TotalAskVolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalBidVol
        {
            get
            {
                return this.TotalBidVolField;
            }
            set
            {
                this.TotalBidVolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TradingDay
        {
            get
            {
                return this.TradingDayField;
            }
            set
            {
                this.TradingDayField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Turnover
        {
            get
            {
                return this.TurnoverField;
            }
            set
            {
                this.TurnoverField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Volume
        {
            get
            {
                return this.VolumeField;
            }
            set
            {
                this.VolumeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint WeightedAvgAskPrice
        {
            get
            {
                return this.WeightedAvgAskPriceField;
            }
            set
            {
                this.WeightedAvgAskPriceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint WeightedAvgBidPrice
        {
            get
            {
                return this.WeightedAvgBidPriceField;
            }
            set
            {
                this.WeightedAvgBidPriceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WindCode
        {
            get
            {
                return this.WindCodeField;
            }
            set
            {
                this.WindCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YieldToMaturity
        {
            get
            {
                return this.YieldToMaturityField;
            }
            set
            {
                this.YieldToMaturityField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://MarketInfoSys", ConfigurationName = "IStockInfo")]
public interface IStockInfo
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://MarketInfoSys/IStockInfo/DoWork", ReplyAction = "http://MarketInfoSys/IStockInfo/DoWorkResponse")]
    int DoWork(int a, int b);

    [System.ServiceModel.OperationContractAttribute(Action = "http://MarketInfoSys/IStockInfo/DoWork2", ReplyAction = "http://MarketInfoSys/IStockInfo/DoWork2Response")]
    int DoWork2(int a, int b);

    [System.ServiceModel.OperationContractAttribute(Action = "http://MarketInfoSys/IStockInfo/DeQueueInfo", ReplyAction = "http://MarketInfoSys/IStockInfo/DeQueueInfoResponse")]
    marketinfosys.MarketData DeQueueInfo();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IStockInfoChannel : IStockInfo, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class StockInfoClient : System.ServiceModel.ClientBase<IStockInfo>, IStockInfo
{

    public StockInfoClient()
    {
    }

    public StockInfoClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public StockInfoClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public StockInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public StockInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public int DoWork(int a, int b)
    {
        return base.Channel.DoWork(a, b);
    }

    public int DoWork2(int a, int b)
    {
        return base.Channel.DoWork2(a, b);
    }

    public marketinfosys.MarketData DeQueueInfo()
    {
        return base.Channel.DeQueueInfo();
    }
}
